sudo: required
language: python
services:
- docker
env:
  global:
  - secure: NPabsGqukbVT17pAgeRcKgY0Z/RmwNcJTnHdW5eVD2LOsMZ8Xlr1WyAT3e4Nwqv2yDQG5ch9K3ZklKQYVYKaAsPdJRo3fyRt1rqnHwxKrO6AWvnVivYhhGiDc5xzmUgRc8qR1tWhaIdK2Pq+Yv8M/HsMTg6tHDMTiK7N5W4a3GASz1/2SKrP35niF08cBQbpmPLUu45G7uaHyolNjqI9t9uVquP58OfX00rTMM+KOOLkqXFrG2pdjuqsEnOG5vR80CqxZUSPFlULDsW0xY7mTKqFWmNphza5N6EpBB/sx0Jq6QeK8Rw3zyQLEkvJRqd0nwTPkOnTa63SD6m5rqBgY3/kbyAllh4TdkfQkx2JYTRC6vQiZGWt9TPJThiG6O1N/IvBnR5zrfgbb0Ed8VL1OI/6k+xpqOF9+sc+GD5r7pZjRtyot5L341TqP2mkXxdSvVos0fiERuxWm87585eNb7S47CKQVG5wqIkIPlwotInuwcqVQKu1c6x2beTZVbNbNtHwvd13EZW3yLJLqTh5opS+Sdp4aknARQZbZd+zVrauTo0mZeen0/u+Mp6xwC5bzzyqHeDybXH5cpyD04psJxmF7cqAML3pVGjPRl6K9iotY8mXD8pViAeKaZl0f+mZ9t5rr1QszbuX05ysPG7z9zL1c4Sp2A9o/qb5oeTf5PI=
  - secure: YvQLiijmIHfvZo4PgBOG5J/muJCmgjL/y1Ds+ZPLtxIlZyMB+pOpf0sGYIHevRgWDggRf0PxTBTGhyY7qNgjdZqc50muxDSMwwF4u9SsPaz02LMOdq+XdAW67CD3dsK5DsG1E8spy1Y/QK18L6+KMUdLKlA/dR9AsREU8rawuTpjNDpJCD+03VB2ve+cAD/taKCUots6vP9rPe1Wut33F6WXvvTfE/Q69TVaoTjRCGOSOqNoHvWRwG54EJSrOaR0LfDkC91aXSqQgq190T/QeSFQ0hoapibm0S9BDrn8mlNtjV0bChMiBDi/XpwIJOhACCbGlt6GZn9E3IbM/lKDE8bBVtOOdzQxKtS4izA5KywKUWJNXRxv/W7PJIR/KAV6w482q5d3C0gleAxIPBSF/9xkkeRqYXpHwCYZIZvpcOgbaiWBqkeg31QoWrprTE6jAv/r9DO/cavgkH3uQqLrtJrEk+BN4HTIWkHmg35Le/+5ouHSkQkgmBW/vvqNjObooOjaN8wc7cl4DCfKgnfQSdGhq8MgssJ0BWvY57vE5Ie5kfaWKbGQWkYTkYmIBjh+hF63OmaTCq8WCndypelMfbYI7z/+EZYZRPlFhc3wjTt30+sE9sz9De93pwhXeK+Tns6ZlE+Riqeopo0C/6pSzXvW2lhozElBEW4Vtemcv2s=
  - secure: BpHncbGmkhwtwqO+sHx0bf2WDFw5ZSWTu2McyLKBYie0Kwum3hZROEjWwqxOjPkLdfIwLYBzsGTiYxS6aVat5jw59zcQtIRQid8dR3YrNnVExuZiIOi9Byf+wAUq1zhKN8DjmNDrp6sbTr794LcXOkJjmjqvRm0dVCr/qAtaHR1NRvcCVr+hpOac77QfeF8d6DQ+kxgtMnRb6YUPxK4gEJ0I781p0CBbjecrwe1yWSpJXsMQXsbgXTiVHH8eGyENrP4/pGSt6zZliy0LfvR22JOURMA8MABonZHkdTcc6X3g5aqMirHuEbXWBXPHsVZDhWVEhrncqZ7aRTpS4YcErR2t5Tzk8UTbRaT1a3sH/d/PmS4SCCK2eHMjaMKjB4CWMrjCKlnwTp6Y33VOsjZ6m3isbQop3Zh2gU0f7eadW9rnyQIjLUedEFFBXzm8KFtSF7Kb/9+nn67cPZipX7uPoVkE9wO+a7Gv79smF+Tz87QSE81+OWgnFqwRA+D48AcoLCzTb8mlvH9N/d1m2Yb08kysXeea48CBFVNbN/jGTrzHKikkWpPFMCyHJ5uqjwnnjZxpMxg7eucNWXgvJGxljLo9ORV22eyom6jQ+BTC4haRFH+ocipV+Tk9jEHkN4bMYMehwaxeBZK22Kb7RGJuu0ea0W/Yu1C5X6418N0mlsg=
before_install:
- pip install awscli
- export PATH=$PATH:$HOME/.local/bin
- bash bin/aws_credentials.sh
script:
- docker build -t 119933218031.dkr.ecr.us-east-1.amazonaws.com/airflow-base .
deploy:
  provider: script
  script: bash bin/ecr_push.sh
  on:
    branch: master
