sudo: required
language: python
services:
- docker
env:
  global:
  - secure: aRrZIrR+D+JS6ChNm+zGDYq+dxcvCN90SKt/d8/D92Emm4wMY8NsrPldq3gNDk7YLru9T9fSGh+Ui8nd9UTrdBtWrugCJ7WY2zN4UQZsQLw9+XUy3ONxb4J0zOa/O8ETWqUvRCjKIGHkGJN7LVXiyrLdbgDIsAyyZ3JeZfQYzC4OFnkGuJIRdzDAsJqNciB9A5thx6bBDRIg6LIDljKWcMvWSKJMO76YBgyWdbNtwYjCyNRpwcpx6aXXAmlDB3BLb5xxtsPSSYVOdoRaiPkJTZdlLpHEh+NEFBM9eilc1/9wxP3h4xS54HVmWpmeI/8HPN0SgiYoEkOHzqMkhl/AoziFysEAwLyrulRPJlE1gp3vjxeyt/aAAAWCKOlaR1Le9vJYNAvdg+pcJmIq8+6LotCU83FyuPE/4DFhVtaG8cS9ijB5jD6YQ94Rc2rsve/LM2ZlwvOI9xP5cAH/jZXwUejUDwOCVpUacjJnRVuq1AYOy9VxJY/W1qSY7gG01nSreGKuoZePvxrSbw0t+2ImCiBwEEZ0iwXZXtfw9FVArjuiahd7lKPGQKZga72MdlDzEvjTRopG31/JUCpRUsSalXr69f8EfW0k3OSQsxw0z4Dx9moUaT3Wai/pBQyrHS8cofjXvUAQSvj5AarIayqJegVkI2uS//VPqotoJir71Vs=
  - secure: eoMLrrZHYRV74yAXU6DfLf5OaYp0Pu3CKN0EIgYlKKB7p8gwJcoZUh5hvyPGCXyBgVodrZbBffHez98juM/Ls9Y+BBbVC+X1Dp1fCyVzso+t3YzyaC5RdVNk4B8p1cZzeABhr79jk2ldiKCCgfszejynlib0+ZQAC72vbKA/wxaMRzRLi9LyXdAoGVnwkejBkmfQ9wE9xPvvM9qIt1xozc7PhsJvZyflw7ZfpYYV+lC5zNycBHW34mdRiSUfp+sx/WvcBfBqoM/W9Lvt7IgZDOpleHLlfTKKGrXSDkv0NAkynu7TNraxCFn4O8UAVHCyf3iBzGJzx1Xj6C0Z0OpkIbAQnedaJI3jx8BgNkZqMYjD8LK6gyNVIUyfhbBxSGbgaq9lvi/fJp7GVYHTY8JEOIjS+wk2pC4gsBp2tJ9xs2DOLkClf7EvtnpGQycN/grI8FzmLAH7Q6+ZZhgeNHaIbphNnO+8yML3eE7rWub94PDSzWjATQebvIWmZxHYq9Hohi0dITYsye3JQTWaHywdThiMnc20kjgVA9T3p8ixBaGu3hC+HCiLFxFuLs/ehdq9/6JOIU8VJ6DgO9vYFij6bv5rlXlkVhAjXL5zMJjfaR7nNNLpyakqW2i72bx7HR//rYdlpdhfVNe0i0kZ8NgCrX5byx+6oNR3HU+Tipp8MOE=
  - secure: FMf3JhnS2FeHh3ED5ZDUF5K21jkaJQTCJsmWFf0kd66/ekP5ABu+01FOSBXF9VLKAAie8sUX4sNxdbs+Su05KUZ6o96kyqf0w4FEklKyIRrYMfkIB/efjjqdUFI5kFziWSadhyGBuBaKyfGa5gyMxDfAPGIGoC7hA6+dISb5+2wUAmSnn4VhO4U1YKeA8llFU2WJi80ArLEfcCM3Q3fTVzvjFGT2bk42pbEGTCSKUbpGdID8G0ZWRRJmHG6hACVmMTc0MTriYELSJVM/tRBOwp/Ll9AZ6gLlB+c5k5bBBuHNRoKdXa3gv4tX+2V97d6z5890vfhIu+2TzUtnjyyCYloC/eOqVxX/DphT8RJRmuQ8L42jr1Q9zc/WofHLUVmU3HycM0fvYIk79HkgnPMOdb2G1vuvza2UUNxBwmVLalwVYoFqHJIE3S/h+dD9gs0FKlwKC6M8k/9QJPwxhmp0RtQcrOG0hedcRTj8ZK1CCaNej3lvsGzxVJ/BPhKTnjhKRYZIb8ycJ3dPT4LyO58ITESz6YlV23mJNyBraQ+6X2G12WmtXc2NY0/YX8mb3bEqAZJ3LfQqtGxi9xGI5V8kMo7qCH3uDq0TDo3sGndTgUej6F+L1SSgpgl21u8rvhzjLPFGFEN0ja5L5lGulm8xhjXjGeP/+kG1JCsT6NhR6mA=
before_install:
- pip install awscli
- export PATH=$PATH:$HOME/.local/bin
- bash bin/aws_credentials.sh
script:
- docker build -t 119933218031.dkr.ecr.us-east-1.amazonaws.com/airflow-base .
deploy:
  provider: script
  script: bash bin/ecr_push.sh
  on:
    branch: master
