sudo: required
language: python
services:
  - docker
before_install:
  - docker --version
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
script:
  - eval $(aws ecr get-login --no-include-email --region us-east-1)
  - docker pull 119933218031.dkr.ecr.us-east-1.amazonaws.com/airflow-base:latest
  - docker build -t 119933218031.dkr.ecr.us-east-1.amazonaws.com/airflow-base .
deploy:
  provider: script
  script: bash bin/ecr_push.sh
  on:
    branch: master
